name: Multi-Job Workflow
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Build Go Binary
        run: go build -o main main.go

      - name: run Binary
        run: ./main


  windows:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Build Go binary
        run: go build -o main.exe main.go

      - name: Run binary
        run: .\main.exe

  macos:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Build Go Binary
        run: go build -o main main.go

      - name: run Binary
        run: ./main


  cross-compile:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20

      - name: Cross-compile for all platforms
        run: |
          echo "Cross compiling for all platforms:"
          echo "Cross compiling for all platforms:"
          GOOS=linux   GOARCH=amd64 go build -o main-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o main-windows-amd64.exe .
          GOOS=darwin  GOARCH=amd64 go build -o main-darwin-amd64 .
      
      - name: list binaries
        run: ls -l
      
